server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: capstone
    password: password
  jpa:
    open-in-view: false
    properties:
      hibernate:
        search:
          backend:
            type: lucene
            directory.root: ./backend/spring/data/index
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cs420
          jwk-set-uri: http://localhost:8080/realms/cs420/protocol/openid-connect/certs

capstone:
  jwt:
    issuerUri: http://localhost:8080/realms/cs420

