server:
  port: 9001

spring:
  datasource:
    url: jdbc:h2:file:./backend/database/h2
    username: capstone
    password: password

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:

        search:
          backend:
            type: lucene
            directory.root: ./backend/spring/data/index
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/cs420
